import type { Metadata } from "next";
import "./globals.css";
import '../styles/globals.css';
import RecoidContextProvider from "./recoilContextProvider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Practice DSA</title>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <link rel="icon" href="/dsa-logo.png"/>
        <meta name="description" content="DSA practice and examples application"/>
      </head>
      {/* <body className={inter.className}>{children}</body> */}
      <RecoidContextProvider>


      <ToastContainer/>

        {children}</RecoidContextProvider>
    </html>
  );
}
